apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-IaaC
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/anilnokia/gitops.git
    targetRevision: HEAD
    path: iaac
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
