apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: airflow
    server: https://kubernetes.default.svc
  project: production
  source:
    path: apps/airflow
    repoURL: https://github.com/anilnokia/gitops.git
    targetRevision: HEAD
