apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-blipp56
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubeflow
    server: https://135.104.238.128:6443
  project: default
  source:
    path: apps/kubeflow
    repoURL: https://github.com/anilnokia/gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

