apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-gitlab
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlabe2.ext.net.nokia.com/bl-sdp/mlaas.git
    targetRevision: HEAD
    path: gitops/apps/nginx
  destination:
    server: https://135.104.238.128:6443
    namespace: nginx
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
