apiVersion: "kubeflow.org/v1"
kind: TFJob
metadata:
  name: tfjob-mnist
spec:
   tfReplicaSpecs:
     Worker:
       replicas: 1
       restartPolicy: OnFailure
       template:
         metadata:
           labels:
             app: tfjob
         spec:
           containers:
             - name: tensorflow
               image: docker-registry.sdp.research.bell-labs.com:5000/mlaas/mnist_tf2:1.0
               imagePullPolicy: Always
               volumeMounts:
                 - name: datasets
                   mountPath: /nas4/brianfri/datasets
               env:
                 - name: HTTP_PROXY
                   value: "http://proxy.lbs.alcatel-lucent.com:8000"
                 - name: HTTPS_PROXY
                   value: "http://proxy.lbs.alcatel-lucent.com:8000"
                 - name: http_proxy
                   value: "http://proxy.lbs.alcatel-lucent.com:8000"
                 - name: https_proxy
                   value: "http://proxy.lbs.alcatel-lucent.com:8000"
                 - name: NUM_EPOCHS
                   value: "10"
                 - name: SAVE_DIR
                   value: "/tmp"
                 - name: DATA_DIR
                   value: "/nas4/brianfri/datasets"
                 - name: TENSORBOARD_DIR
                   value: "/nas4/brianfri/tensorboard/mnist"
                 - name: KEEP_RUNNING
                   value: "true"
           volumes:
             - name: datasets
               hostPath:
                 path: /nas4/brianfri/datasets
---
apiVersion: v1
kind: Service
metadata:
  name: tfjob-service
  labels:
    app: tfjob
spec:
  type: NodePort
  ports:
  - port: 6006
    nodePort: 6006
    targetPort: 6006
    protocol: TCP
  selector:
    app: tfjob
