apiVersion: "kubeflow.org/v1"
kind: TFJob
metadata:
  name: tfjob-mnist
  namespace: kubeflow
spec:
   tfReplicaSpecs:
     Worker:
       replicas: 2
       restartPolicy: OnFailure
       template:
         spec:
           containers:
             - name: tensorflow
               image: bl-ansr-docker-local.artifactory-fpark1.int.net.nokia.com/mlaas/mnist_tf2:1.0
               env:
                 - name: HTTP_PROXY
                   value: "http://proxy.lbs.alcatel-lucent.com:8000"
                 - name: HTTPS_PROXY
                   value: "http://proxy.lbs.alcatel-lucent.com:8000"
                 - name: http_proxy
                   value: "http://proxy.lbs.alcatel-lucent.com:8000"
                 - name: https_proxy
                   value: "http://proxy.lbs.alcatel-lucent.com:8000"
                 - name: NUM_EPOCHS
                   value: "10"
                 - name: SAVE_DIR
                   value: "/tmp"

